spring:
  data:
    mongodb:
      uri: mongodb://qmgo:120211@cloudmo.top:27017/qmgo
  session:
    store-type: redis
  redis:
    database: 0
    host: cloudmo.top
    password: 120211
    port: 6379
logging:
  level:
    root: debug
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
  servlet:
    session:
      timeout: 30m
    context-path: /v1
config:
  jwt:
    secret: sadfaewaf
    expire: 6000