spring:
  data:
    mongodb:
      username: todo
      database: todo
      password: WjC120211
      host: cloudmo.top
      port: 27017
  session:
    store-type: redis
  redis:
    database: 0
    host: cloudmo.top
    password: wjc120211
    port: 6379
logging:
  level:
    root: warn
server:
  port: 8088
  error:
    path: /error
  tomcat:
    uri-encoding: utf-8
  servlet:
    session:
      timeout: 30m
    context-path: /v1
config:
  jwt:
    secret: sadfaewaf
    expire: 6000