spring:
  profiles:
    include: common
  session:
    store-type: redis
logging:
  level:
    root: warn
server:
  port: 8088
  error:
    path: /error
  tomcat:
    uri-encoding: utf-8
  servlet:
    session:
      timeout: 30m
    context-path: /v1